// Code generated by protoc-gen-go. DO NOT EDIT.
// source: parking-services.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterParkingRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	PlatNo               string   `protobuf:"bytes,2,opt,name=platNo,proto3" json:"platNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterParkingRequest) Reset()         { *m = RegisterParkingRequest{} }
func (m *RegisterParkingRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterParkingRequest) ProtoMessage()    {}
func (*RegisterParkingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc30adc9331bb405, []int{0}
}

func (m *RegisterParkingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterParkingRequest.Unmarshal(m, b)
}
func (m *RegisterParkingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterParkingRequest.Marshal(b, m, deterministic)
}
func (m *RegisterParkingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterParkingRequest.Merge(m, src)
}
func (m *RegisterParkingRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterParkingRequest.Size(m)
}
func (m *RegisterParkingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterParkingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterParkingRequest proto.InternalMessageInfo

func (m *RegisterParkingRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *RegisterParkingRequest) GetPlatNo() string {
	if m != nil {
		return m.PlatNo
	}
	return ""
}

type RegisterParkingResponse struct {
	Code                 string               `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string               `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *RegisterParkingData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RegisterParkingResponse) Reset()         { *m = RegisterParkingResponse{} }
func (m *RegisterParkingResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterParkingResponse) ProtoMessage()    {}
func (*RegisterParkingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc30adc9331bb405, []int{1}
}

func (m *RegisterParkingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterParkingResponse.Unmarshal(m, b)
}
func (m *RegisterParkingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterParkingResponse.Marshal(b, m, deterministic)
}
func (m *RegisterParkingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterParkingResponse.Merge(m, src)
}
func (m *RegisterParkingResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterParkingResponse.Size(m)
}
func (m *RegisterParkingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterParkingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterParkingResponse proto.InternalMessageInfo

func (m *RegisterParkingResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RegisterParkingResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *RegisterParkingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterParkingResponse) GetData() *RegisterParkingData {
	if m != nil {
		return m.Data
	}
	return nil
}

type RegisterParkingData struct {
	StatusParking        string   `protobuf:"bytes,1,opt,name=statusParking,proto3" json:"statusParking,omitempty"`
	InvoiceNo            string   `protobuf:"bytes,2,opt,name=invoiceNo,proto3" json:"invoiceNo,omitempty"`
	EnteredDate          string   `protobuf:"bytes,3,opt,name=enteredDate,proto3" json:"enteredDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterParkingData) Reset()         { *m = RegisterParkingData{} }
func (m *RegisterParkingData) String() string { return proto.CompactTextString(m) }
func (*RegisterParkingData) ProtoMessage()    {}
func (*RegisterParkingData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc30adc9331bb405, []int{2}
}

func (m *RegisterParkingData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterParkingData.Unmarshal(m, b)
}
func (m *RegisterParkingData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterParkingData.Marshal(b, m, deterministic)
}
func (m *RegisterParkingData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterParkingData.Merge(m, src)
}
func (m *RegisterParkingData) XXX_Size() int {
	return xxx_messageInfo_RegisterParkingData.Size(m)
}
func (m *RegisterParkingData) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterParkingData.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterParkingData proto.InternalMessageInfo

func (m *RegisterParkingData) GetStatusParking() string {
	if m != nil {
		return m.StatusParking
	}
	return ""
}

func (m *RegisterParkingData) GetInvoiceNo() string {
	if m != nil {
		return m.InvoiceNo
	}
	return ""
}

func (m *RegisterParkingData) GetEnteredDate() string {
	if m != nil {
		return m.EnteredDate
	}
	return ""
}

type ValidationParkingResponse struct {
	Code                 string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *ValidationParkingData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ValidationParkingResponse) Reset()         { *m = ValidationParkingResponse{} }
func (m *ValidationParkingResponse) String() string { return proto.CompactTextString(m) }
func (*ValidationParkingResponse) ProtoMessage()    {}
func (*ValidationParkingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc30adc9331bb405, []int{3}
}

func (m *ValidationParkingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationParkingResponse.Unmarshal(m, b)
}
func (m *ValidationParkingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationParkingResponse.Marshal(b, m, deterministic)
}
func (m *ValidationParkingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationParkingResponse.Merge(m, src)
}
func (m *ValidationParkingResponse) XXX_Size() int {
	return xxx_messageInfo_ValidationParkingResponse.Size(m)
}
func (m *ValidationParkingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationParkingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationParkingResponse proto.InternalMessageInfo

func (m *ValidationParkingResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ValidationParkingResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ValidationParkingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ValidationParkingResponse) GetData() *ValidationParkingData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ValidationParkingData struct {
	QrContent            string   `protobuf:"bytes,1,opt,name=qrContent,proto3" json:"qrContent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidationParkingData) Reset()         { *m = ValidationParkingData{} }
func (m *ValidationParkingData) String() string { return proto.CompactTextString(m) }
func (*ValidationParkingData) ProtoMessage()    {}
func (*ValidationParkingData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc30adc9331bb405, []int{4}
}

func (m *ValidationParkingData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationParkingData.Unmarshal(m, b)
}
func (m *ValidationParkingData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationParkingData.Marshal(b, m, deterministic)
}
func (m *ValidationParkingData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationParkingData.Merge(m, src)
}
func (m *ValidationParkingData) XXX_Size() int {
	return xxx_messageInfo_ValidationParkingData.Size(m)
}
func (m *ValidationParkingData) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationParkingData.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationParkingData proto.InternalMessageInfo

func (m *ValidationParkingData) GetQrContent() string {
	if m != nil {
		return m.QrContent
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterParkingRequest)(nil), "v1.RegisterParkingRequest")
	proto.RegisterType((*RegisterParkingResponse)(nil), "v1.RegisterParkingResponse")
	proto.RegisterType((*RegisterParkingData)(nil), "v1.RegisterParkingData")
	proto.RegisterType((*ValidationParkingResponse)(nil), "v1.ValidationParkingResponse")
	proto.RegisterType((*ValidationParkingData)(nil), "v1.ValidationParkingData")
}

func init() { proto.RegisterFile("parking-services.proto", fileDescriptor_fc30adc9331bb405) }

var fileDescriptor_fc30adc9331bb405 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x4f, 0x6f, 0xd3, 0x3e,
	0x18, 0x96, 0xdb, 0x6a, 0xd3, 0x3c, 0xfd, 0xf4, 0x9b, 0x8c, 0xe8, 0xda, 0x32, 0xa4, 0x28, 0x02,
	0x31, 0x95, 0x25, 0x69, 0x4b, 0xe1, 0x50, 0x2e, 0x30, 0x76, 0x46, 0x53, 0x90, 0xb8, 0xbb, 0xc9,
	0x2b, 0xd7, 0x2c, 0xb5, 0x33, 0xdb, 0xcd, 0x40, 0xbb, 0x21, 0x4e, 0x88, 0x03, 0x82, 0x1b, 0x77,
	0x3e, 0x11, 0x9f, 0x00, 0x09, 0xbe, 0x07, 0xaa, 0xeb, 0xfe, 0x59, 0x93, 0x03, 0x17, 0x4e, 0xb1,
	0x9f, 0xe7, 0x79, 0xdf, 0xf7, 0xf1, 0x63, 0x07, 0x37, 0x73, 0xaa, 0x2e, 0xb8, 0x60, 0x81, 0x06,
	0x55, 0xf0, 0x04, 0x74, 0x98, 0x2b, 0x69, 0x24, 0xa9, 0x15, 0xfd, 0xce, 0x11, 0x93, 0x92, 0x65,
	0x10, 0xd1, 0x9c, 0x47, 0x54, 0x08, 0x69, 0xa8, 0xe1, 0x52, 0x38, 0x45, 0xe7, 0xc4, 0x7e, 0x92,
	0x80, 0x81, 0x08, 0xf4, 0x15, 0x65, 0x0c, 0x54, 0x24, 0x73, 0xab, 0x28, 0xab, 0xfd, 0x53, 0xdc,
	0x8c, 0x81, 0x71, 0x6d, 0x40, 0x9d, 0x2f, 0x26, 0xc6, 0x70, 0x39, 0x03, 0x6d, 0xc8, 0x01, 0xae,
	0xd3, 0x9c, 0xb7, 0x90, 0x87, 0x8e, 0xf7, 0xe2, 0xf9, 0x92, 0x34, 0xf1, 0x4e, 0x9e, 0x51, 0xf3,
	0x52, 0xb6, 0x6a, 0x16, 0x74, 0x3b, 0xff, 0x13, 0xc2, 0x87, 0xa5, 0x26, 0x3a, 0x97, 0x42, 0x03,
	0x21, 0xb8, 0x91, 0xc8, 0x14, 0x5c, 0x1b, 0xbb, 0x9e, 0xf7, 0xd1, 0x86, 0x9a, 0x99, 0x5e, 0xf6,
	0x59, 0xec, 0x48, 0x0b, 0xef, 0x4e, 0x41, 0x6b, 0xca, 0xa0, 0x55, 0xb7, 0xc4, 0x72, 0x4b, 0x1e,
	0xe2, 0x46, 0x4a, 0x0d, 0x6d, 0x35, 0x3c, 0x74, 0xbc, 0x3f, 0x38, 0x0c, 0x8b, 0x7e, 0xb8, 0x35,
	0xf0, 0x8c, 0x1a, 0x1a, 0x5b, 0x91, 0x7f, 0x8d, 0x6f, 0x55, 0x90, 0xe4, 0x1e, 0xfe, 0x6f, 0x31,
	0xc7, 0x81, 0xce, 0xd2, 0x4d, 0x90, 0x1c, 0xe1, 0x3d, 0x2e, 0x0a, 0xc9, 0x13, 0x58, 0x1d, 0x73,
	0x0d, 0x10, 0x0f, 0xef, 0x83, 0x30, 0xa0, 0x20, 0x3d, 0xa3, 0x66, 0xe9, 0x72, 0x13, 0xf2, 0x3f,
	0x23, 0xdc, 0x7e, 0x4d, 0x33, 0x9e, 0xda, 0x94, 0xff, 0x4d, 0x1a, 0xc1, 0x8d, 0x34, 0xda, 0xf3,
	0x34, 0x4a, 0x23, 0x37, 0xf2, 0x78, 0x8c, 0x6f, 0x57, 0xd2, 0xf3, 0xb3, 0x5e, 0xaa, 0x17, 0x52,
	0x18, 0x10, 0xc6, 0x59, 0x5a, 0x03, 0x83, 0xef, 0x35, 0xfc, 0xbf, 0x53, 0xbf, 0x72, 0x6f, 0x90,
	0x7c, 0x28, 0xdf, 0xf4, 0x8a, 0xeb, 0x54, 0xdc, 0x8a, 0x7b, 0x4b, 0x9d, 0x3b, 0x95, 0xdc, 0x22,
	0x14, 0xbf, 0xf7, 0xfe, 0xc7, 0xaf, 0xaf, 0xb5, 0xae, 0x7f, 0x3f, 0x2a, 0xfa, 0xd1, 0xf6, 0xb3,
	0x8f, 0x94, 0xab, 0x0a, 0x1c, 0x33, 0x42, 0x5d, 0xf2, 0x11, 0xe1, 0xb6, 0xeb, 0xb2, 0x3e, 0xd9,
	0x5f, 0x19, 0xb9, 0x5b, 0x19, 0xd6, 0xca, 0xca, 0xc0, 0x5a, 0x39, 0xf1, 0x1f, 0x54, 0x5a, 0x29,
	0x56, 0x75, 0x1b, 0x66, 0x4e, 0x7f, 0xa3, 0x2f, 0xcf, 0x7f, 0x22, 0x72, 0x8d, 0x0f, 0xce, 0xb7,
	0x0a, 0xfc, 0x71, 0x19, 0x23, 0x4f, 0x26, 0xc6, 0xe4, 0x7a, 0x14, 0x45, 0x8c, 0x9b, 0xc9, 0x6c,
	0x1c, 0x26, 0x72, 0x1a, 0xa5, 0x3c, 0xb9, 0x78, 0xc7, 0x40, 0xd1, 0x2c, 0xe5, 0x91, 0xfd, 0x2f,
	0x83, 0xed, 0xe1, 0x9d, 0xe6, 0xa6, 0xe8, 0x19, 0x9b, 0x52, 0x9e, 0xcd, 0x6b, 0x07, 0xf5, 0x7e,
	0xd8, 0xeb, 0x22, 0x34, 0x38, 0xa0, 0x79, 0x9e, 0xf1, 0xc4, 0xda, 0x8b, 0xde, 0x68, 0x29, 0x46,
	0x25, 0x24, 0x7e, 0x8a, 0xeb, 0xc3, 0xde, 0x90, 0x0c, 0x71, 0x37, 0x06, 0x33, 0x53, 0x02, 0x52,
	0xef, 0x6a, 0x02, 0xc2, 0x33, 0x13, 0xf0, 0x14, 0x68, 0x39, 0x53, 0x09, 0x78, 0xa9, 0x04, 0xed,
	0x09, 0x69, 0x3c, 0x78, 0xcb, 0xb5, 0x09, 0xc9, 0x0e, 0x6e, 0x7c, 0xab, 0xa1, 0xdd, 0xf1, 0x8e,
	0x35, 0xf6, 0xe8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x63, 0xec, 0xb9, 0x9a, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ParkingServicesClient is the client API for ParkingServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ParkingServicesClient interface {
	RegisterParkingServices(ctx context.Context, in *RegisterParkingRequest, opts ...grpc.CallOption) (*RegisterParkingResponse, error)
	ParkingValidationServices(ctx context.Context, in *RegisterParkingRequest, opts ...grpc.CallOption) (*ValidationParkingResponse, error)
}

type parkingServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewParkingServicesClient(cc grpc.ClientConnInterface) ParkingServicesClient {
	return &parkingServicesClient{cc}
}

func (c *parkingServicesClient) RegisterParkingServices(ctx context.Context, in *RegisterParkingRequest, opts ...grpc.CallOption) (*RegisterParkingResponse, error) {
	out := new(RegisterParkingResponse)
	err := c.cc.Invoke(ctx, "/v1.ParkingServices/RegisterParkingServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parkingServicesClient) ParkingValidationServices(ctx context.Context, in *RegisterParkingRequest, opts ...grpc.CallOption) (*ValidationParkingResponse, error) {
	out := new(ValidationParkingResponse)
	err := c.cc.Invoke(ctx, "/v1.ParkingServices/ParkingValidationServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParkingServicesServer is the server API for ParkingServices service.
type ParkingServicesServer interface {
	RegisterParkingServices(context.Context, *RegisterParkingRequest) (*RegisterParkingResponse, error)
	ParkingValidationServices(context.Context, *RegisterParkingRequest) (*ValidationParkingResponse, error)
}

// UnimplementedParkingServicesServer can be embedded to have forward compatible implementations.
type UnimplementedParkingServicesServer struct {
}

func (*UnimplementedParkingServicesServer) RegisterParkingServices(ctx context.Context, req *RegisterParkingRequest) (*RegisterParkingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterParkingServices not implemented")
}
func (*UnimplementedParkingServicesServer) ParkingValidationServices(ctx context.Context, req *RegisterParkingRequest) (*ValidationParkingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParkingValidationServices not implemented")
}

func RegisterParkingServicesServer(s *grpc.Server, srv ParkingServicesServer) {
	s.RegisterService(&_ParkingServices_serviceDesc, srv)
}

func _ParkingServices_RegisterParkingServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterParkingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServicesServer).RegisterParkingServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ParkingServices/RegisterParkingServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServicesServer).RegisterParkingServices(ctx, req.(*RegisterParkingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParkingServices_ParkingValidationServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterParkingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParkingServicesServer).ParkingValidationServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ParkingServices/ParkingValidationServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParkingServicesServer).ParkingValidationServices(ctx, req.(*RegisterParkingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ParkingServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ParkingServices",
	HandlerType: (*ParkingServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterParkingServices",
			Handler:    _ParkingServices_RegisterParkingServices_Handler,
		},
		{
			MethodName: "ParkingValidationServices",
			Handler:    _ParkingServices_ParkingValidationServices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parking-services.proto",
}
